set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN Y18 [get_ports clk]
set_property PACKAGE_PIN F15 [get_ports rst]
set_property PACKAGE_PIN M15 [get_ports uart_tx]
set_property PACKAGE_PIN M22 [get_ports {led[0]}]
set_property PACKAGE_PIN N22 [get_ports {led[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports tx_done]
set_property IOSTANDARD LVCMOS33 [get_ports uart_state]
set_property PACKAGE_PIN M22 [get_ports tx_done]
set_property PACKAGE_PIN N22 [get_ports uart_state]
