set_property SRC_FILE_INFO {cfile:D:/Project/FPGA/024_UART_RS232_Sendonebyte/UART_RS232_Sendonebyte/UART_RS232_Sendonebyte.srcs/constrs_1/new/UART_Sendonebyte.xdc rfile:../../../UART_RS232_Sendonebyte.srcs/constrs_1/new/UART_Sendonebyte.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y18 [get_ports clk]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports uart_tx]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M22 [get_ports uart_state]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N22 [get_ports tx_done]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F15 [get_ports rst]
