set_property SRC_FILE_INFO {cfile:D:/Project/FPGA/028_UART_RS232_RXD_Ctrl_Led/028_UART_RS232_RXD_Ctrl_Led.srcs/constrs_1/new/UART_RXD_Ctrl_Led.xdc rfile:../../../028_UART_RS232_RXD_Ctrl_Led.srcs/constrs_1/new/UART_RXD_Ctrl_Led.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y18 [get_ports clk]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M22 [get_ports led]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F15 [get_ports rst]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J21 [get_ports uart_rx]
