set_property SRC_FILE_INFO {cfile:D:/Project/FPGA/025_UART_RS232_Sendmultiplebyte/UART_Sendmultiplebyte/UART_Sendmultiplebyte.srcs/constrs_1/new/UART_Sendmultiplebytes.xdc rfile:../UART_Sendmultiplebyte.srcs/constrs_1/new/UART_Sendmultiplebytes.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M22 [get_ports {led[0]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N22 [get_ports {led[1]}]
